"""Public domain model API."""

from .backup import Backup
from .compression import (
    CompressionCancelled,
    CompressionFile,
    CompressionHistoryEntry,
    CompressionMeasurement,
    CompressionPlan,
    CompressionPlanRejected,
    CompressionProviderError,
    CompressionResult,
    CompressionToolCapabilities,
)
from .enums import (
    AutomaticCompressionMode,
    BackupStatus,
    CapabilityStatus,
    CompressionProfile,
    ControllerMode,
    FilesystemType,
    GameStatus,
    Launcher,
    LogLevel,
    OptimizationProfile,
    PostLaunchBehavior,
    SessionType,
    SizeScanStatus,
    TaskStatus,
    TaskType,
    TextureCompatibility,
    TextureMode,
    TextureScope,
    ThemeMode,
)
from .gamepad import GamepadAction, GamepadDevice, GamepadEvent, GamepadType, button_hints
from .game import (
    AnalysisReport,
    CompressionEstimate,
    CompressionModeInfo,
    Game,
    OptimizationCompatibility,
    OptimizationOptions,
    TextureOptions,
    TexturePreview,
)
from .settings import AppSettings
from .mangohud import (
    MANGOHUD_METRICS,
    MANGOHUD_POSITIONS,
    MANGOHUD_PRESETS,
    MANGOHUD_SCHEMA_VERSION,
    MangoHudProfile,
    PRESET_METRICS,
    validate_app_id,
)
from .system import FilesystemInfo, SystemInfo
from .optimization_profile import (
    FPS_MODES,
    GAME_CATEGORIES,
    GAMESCOPE_FILTERS,
    GAMESCOPE_MODES,
    GAMESCOPE_SCALERS,
    OPTIMIZATION_PRESETS,
    OPTIMIZATION_SCHEMA_VERSION,
    USER_GOALS,
    GameOptimizationProfile,
)
from .optiscaler import (
    OPTISCALER_PROXY_DLLS,
    OPTISCALER_SCHEMA_VERSION,
    OPTISCALER_STATES,
    OptiScalerProfile,
)
from .task import TERMINAL_TASK_STATUSES, Task

__all__ = [
    "AnalysisReport",
    "AutomaticCompressionMode",
    "AppSettings",
    "Backup",
    "BackupStatus",
    "CapabilityStatus",
    "CompressionEstimate",
    "CompressionCancelled",
    "CompressionFile",
    "CompressionHistoryEntry",
    "CompressionMeasurement",
    "CompressionModeInfo",
    "CompressionPlan",
    "CompressionPlanRejected",
    "CompressionProfile",
    "CompressionProviderError",
    "CompressionResult",
    "CompressionToolCapabilities",
    "ControllerMode",
    "FilesystemInfo",
    "FilesystemType",
    "Game",
    "GameOptimizationProfile",
    "GAME_CATEGORIES",
    "GAMESCOPE_FILTERS",
    "GAMESCOPE_MODES",
    "GAMESCOPE_SCALERS",
    "FPS_MODES",
    "OPTIMIZATION_PRESETS",
    "OPTIMIZATION_SCHEMA_VERSION",
    "USER_GOALS",
    "GameStatus",
    "GamepadAction",
    "GamepadDevice",
    "GamepadEvent",
    "GamepadType",
    "Launcher",
    "MANGOHUD_METRICS",
    "MANGOHUD_POSITIONS",
    "MANGOHUD_PRESETS",
    "MANGOHUD_SCHEMA_VERSION",
    "MangoHudProfile",
    "LogLevel",
    "OptimizationCompatibility",
    "OptimizationOptions",
    "OptimizationProfile",
    "OPTISCALER_PROXY_DLLS",
    "OPTISCALER_SCHEMA_VERSION",
    "OPTISCALER_STATES",
    "OptiScalerProfile",
    "PostLaunchBehavior",
    "PRESET_METRICS",
    "SessionType",
    "SizeScanStatus",
    "SystemInfo",
    "TERMINAL_TASK_STATUSES",
    "Task",
    "TaskStatus",
    "TaskType",
    "TextureCompatibility",
    "TextureMode",
    "TextureOptions",
    "TexturePreview",
    "TextureScope",
    "ThemeMode",
    "button_hints",
    "validate_app_id",
]
