"""Application services, including read-only scanning and demo workflows."""

from .analysis_cache import (
    ANALYSIS_CACHE_FORMAT_VERSION,
    AnalysisCache,
    AnalysisCacheError,
)
from .analysis_tasks import BtrfsAnalysisTaskService
from .archive_reader import (
    ArchiveEntry,
    ArchiveReadError,
    ArchiveReader,
    SevenZipArchiveReader,
    ZipArchiveReader,
    open_archive,
)
from .benchmark_estimates import (
    LOW_ADDITIONAL_BENEFIT_BYTES,
    LOW_ADDITIONAL_BENEFIT_FRACTION,
    BenchmarkEstimateCatalog,
    current_compression_saving,
    normalized_benchmark_projection,
)
from .compression_summary import (
    ALMOST_NO_EXCLUSIVE_FRACTION,
    LARGE_SHARED_EXTENT_BYTES,
    LOW_COMPRESSION_EFFECT_FRACTION,
    MODERATE_COMPRESSION_EFFECT_FRACTION,
    STRONG_COMPRESSION_EFFECT_FRACTION,
    aggregate_library_compression,
    classify_compression_effect,
    compression_effect,
    has_high_shared_extent_risk,
    reclaimed_by_last_operation,
)
from .compression import CompressionExecutionProvider, CompressionService
from .compression_history import (
    COMPRESSION_HISTORY_FORMAT_VERSION,
    CompressionHistoryError,
    CompressionHistoryStore,
)

from .backups import (
    BackupNotFoundError,
    BackupServiceError,
    DemoBackupService,
    MockBackupService,
    demo_backups,
)
from .btrfs_analysis import (
    ANALYZER_VERSION,
    AUTO_LEVELS,
    AnalysisCancelled,
    AnalysisLimits,
    AnalysisProgress,
    BtrfsAnalysisReport,
    BtrfsCompressionAnalyzer,
    BtrfsDuResult,
    CompsizeResult,
    InvalidAnalysisPath,
    PROFILE_LEVELS,
    ProfileEstimate,
)
from .contracts import BackupService, TaskService
from .directory_size import DirectorySizeResult, DirectorySizeScanner
from .displays import DisplayDetector, DisplayProfile
from .optimization_advisor import (
    OptimizationAdvisor,
    OptimizationRecommendation,
    SessionPerformanceData,
)
from .optimization_profiles import (
    OPTIMIZATION_FILE_NAME,
    GameOptimizationProfileRepository,
)
from .optimization_runtime import (
    GameRuntimeLaunchPlan,
    OptimizationLaunchPlanner,
    RuntimeToolAvailability,
    RuntimeToolDetector,
)
from .optiscaler import (
    MANIFEST_FORMAT_VERSION as OPTISCALER_MANIFEST_FORMAT_VERSION,
    OptiScalerCancelled,
    OptiScalerConflict,
    OptiScalerConflictError,
    OptiScalerError,
    OptiScalerFilePlan,
    OptiScalerInstallPlan,
    OptiScalerProfileRepository,
    OptiScalerService,
    merge_wine_dll_overrides,
)
from .optiscaler_online import (
    CachedOptiScalerArchive,
    OptiScalerCacheError,
    OptiScalerDownloadError,
    OptiScalerMetadataError,
    OptiScalerNetworkError,
    OptiScalerOnlineError,
    OptiScalerRelease,
    OptiScalerReleaseAsset,
    OptiScalerReleaseClient,
    parse_latest_stable_release,
)
from .proton_tweaks import (
    PROTON_TWEAKS_FILE_NAME,
    ProtonTweaksError,
    ProtonTweaksRepository,
)
from .runner_integration import DEFAULT_RUNNER_PATH, RunnerIntegration, RunnerStatus
from .library_cache import (
    CACHE_FORMAT_VERSION,
    LibraryCache,
    LibraryCacheError,
)
from .mangohud import (
    CONFIG_FILE_NAME as MANGOHUD_CONFIG_FILE_NAME,
    FLATPAK_MANGOHUD_PREFIX,
    FLATPAK_STEAM_APP_ID,
    KNOWN_CONFIG_KEYS,
    METRIC_CONFIG_KEYS,
    MangoHudAvailability,
    MangoHudApplicationConfigStatus,
    MangoHudConfigWriter,
    MangoHudDetector,
    MangoHudLaunchActivation,
    MangoHudLaunchIntegration,
    MangoHudProfileRepository,
)
from .game_executable import (
    ExecutableCandidate,
    ExecutableResolution,
    GameExecutableResolver,
)
from .game_analysis import GameAnalyzer
from .game_settings import (
    ConfigAdapter,
    GameSettingsAdvisor,
    RedEngineConfigAdapter,
    UnrealConfigAdapter,
)
from .performance_analysis import (
    BottleneckAnalyzer,
    FrameRateAnalyzer,
    MangoHudLogParser,
    compare_measurements,
)
from .performance_session import BaselineSessionRepository
from .narrator_activity import NarratorGameActivityDetector
from .narrator_audio import QtNarratorAudioOutput
from .narrator_capture import (
    CaptureCapabilities,
    CaptureRequest,
    CaptureSessionInfo,
    PortalScreenCaptureProvider,
    PortalScreenCastBackend,
    ScreenCaptureProvider,
)
from .narrator_gstreamer import GStreamerPipeWireTransport, PnmStreamDecoder
from .narrator_ocr import (
    TESSERACT_COMPONENT_ID,
    TESSERACT_MODEL_RELATIVE_PATH,
    TesseractOcrProvider,
)
from .narrator_translation import (
    ARGOS_TRANSLATION_COMPONENT_ID,
    ARGOS_TRANSLATION_MODEL_VERSION,
    ARGOS_TRANSLATION_PROVIDER_ID,
    ArgosCTranslate2TranslationProvider,
)
from .narrator_tts import (
    PIPER_COMPONENT_ID,
    PIPER_CONFIG_RELATIVE_PATH,
    PIPER_MODEL_RELATIVE_PATH,
    PIPER_PROVIDER_ID,
    PIPER_VOICE_ID,
    PIPER_VOICE_VERSION,
    POLISH_VOICES,
    PiperPolishTtsProvider,
    PolishVoice,
)
from .narrator_portal import PortalStream, QtPortalScreenCastBackend, QtScreenCastPortal
from .narrator_components import (
    DEFAULT_NARRATOR_COMPONENTS,
    NarratorComponentArtifact,
    NarratorComponentDefinition,
    NarratorComponentManager,
)
from .narrator_persistence import (
    CaptureGrantRepository,
    NarratorSettingsRepository,
    TranslationCache,
    normalize_cache_phrase,
)
from .narrator_pipeline import (
    GameActivityProvider,
    NarratorAudioOutput,
    NarratorPipeline,
    OcrProvider,
    PhraseDeduplicator,
    SubtitleRegionStabilizer,
    SubtitleSource,
    TranslationProvider,
    TtsProvider,
    UnavailableAudioOutput,
    UnavailableOcrProvider,
    UnavailableTranslationProvider,
    UnavailableTtsProvider,
    crop_frame,
    normalize_subtitle,
)
from .optimization_analysis_state import (
    ANALYSIS_STATE_FILE_NAME,
    ANALYSIS_STATE_SCHEMA_VERSION,
    OptimizationAnalysisRepository,
)
from .automatic_optimization import (
    AUTOMATIC_OPTIMIZATION_FILE_NAME,
    AUTOMATIC_OPTIMIZATION_SCHEMA_VERSION,
    AutomaticOptimizationEvaluator,
    AutomaticOptimizationPlan,
    AutomaticOptimizationRepository,
    AutomaticOptimizationResult,
    CandidateApplicability,
    OptimizationProblem,
    RuntimeCandidateRegistry,
    RuntimeOptimizationCandidate,
    diagnose_problem,
    optimization_context_hash,
    verify_runtime_activation,
)
from .game_optimization import (
    GameRecommendationEngine,
    OptimizationChangeService,
)
from .gamepad import GamepadInputMapper, GamepadService
from .game_updates import (
    UPDATE_STATE_FORMAT_VERSION,
    FileFingerprint,
    FingerprintLimits,
    FingerprintSnapshot,
    GameChangeSet,
    GameFingerprintScanner,
    GameUpdateRecord,
    GameUpdateStateStore,
    GameUpdateStatus,
    GameUpdateTracker,
    ManifestObservation,
    UpdateScanCancelled,
    UpdateStateDatabase,
    UpdateStateStoreError,
    diff_fingerprints,
)
from .game_artwork import GameArtworkResolver, ResolvedGameArtwork
from .host_service import (
    HOST_SERVICE_VERSION,
    OPTIONAL_MEASUREMENT_HELPER,
    HostServiceClient,
    HostServiceError,
)
from .host_bootstrap import (
    HostBootstrapError,
    HostBootstrapResult,
    bootstrap_flatpak_host_components,
    default_runner_path,
    host_home_directory,
)
from .settings import SettingsStore, SettingsStoreError
from .tasks import (
    DemoTaskService,
    InvalidTaskTransitionError,
    MockTaskService,
    TaskNotFoundError,
    TaskServiceError,
)
from .task_history import MAX_FINISHED_TASKS, TaskHistoryStore
from .privileged_measurement import (
    PrivilegedMeasurementClient,
    PrivilegedMeasurementError,
    measurement_delta,
)
from .steam_launch import (
    SteamLaunchError,
    SteamLaunchPlan,
    SteamLauncher,
    build_steam_launch_command,
    build_steam_launch_plan,
    uses_flatpak_steam,
)
from .ui_sound import UiSoundService
from .update_display_state import UpdateDisplayStateStore
from .unavailable import (
    FeatureUnavailableError,
    UnavailableBackupService,
    UnavailableTaskService,
)

__all__ = [
    "ANALYSIS_CACHE_FORMAT_VERSION",
    "ANALYZER_VERSION",
    "AUTO_LEVELS",
    "AnalysisCache",
    "AnalysisCacheError",
    "AnalysisCancelled",
    "AnalysisLimits",
    "AnalysisProgress",
    "ArchiveEntry",
    "ArchiveReadError",
    "ArchiveReader",
    "BackupNotFoundError",
    "BackupService",
    "BackupServiceError",
    "BtrfsAnalysisReport",
    "BtrfsAnalysisTaskService",
    "BtrfsCompressionAnalyzer",
    "BenchmarkEstimateCatalog",
    "LOW_ADDITIONAL_BENEFIT_BYTES",
    "LOW_ADDITIONAL_BENEFIT_FRACTION",
    "STRONG_COMPRESSION_EFFECT_FRACTION",
    "MODERATE_COMPRESSION_EFFECT_FRACTION",
    "LOW_COMPRESSION_EFFECT_FRACTION",
    "LARGE_SHARED_EXTENT_BYTES",
    "ALMOST_NO_EXCLUSIVE_FRACTION",
    "COMPRESSION_HISTORY_FORMAT_VERSION",
    "CompressionExecutionProvider",
    "CompressionHistoryError",
    "CompressionHistoryStore",
    "CompressionService",
    "BtrfsDuResult",
    "CompsizeResult",
    "DemoBackupService",
    "DemoTaskService",
    "DirectorySizeResult",
    "DirectorySizeScanner",
    "DisplayDetector",
    "DisplayProfile",
    "OptimizationAdvisor",
    "OptimizationRecommendation",
    "SessionPerformanceData",
    "GameOptimizationProfileRepository",
    "GameAnalyzer",
    "ConfigAdapter",
    "GameSettingsAdvisor",
    "RedEngineConfigAdapter",
    "UnrealConfigAdapter",
    "MangoHudLogParser",
    "BottleneckAnalyzer",
    "FrameRateAnalyzer",
    "BaselineSessionRepository",
    "CaptureCapabilities",
    "CaptureGrantRepository",
    "CaptureRequest",
    "CaptureSessionInfo",
    "DEFAULT_NARRATOR_COMPONENTS",
    "GameActivityProvider",
    "GStreamerPipeWireTransport",
    "NarratorAudioOutput",
    "NarratorComponentArtifact",
    "NarratorComponentDefinition",
    "NarratorComponentManager",
    "NarratorGameActivityDetector",
    "NarratorPipeline",
    "NarratorSettingsRepository",
    "OcrProvider",
    "PhraseDeduplicator",
    "PortalScreenCaptureProvider",
    "PortalStream",
    "PortalScreenCastBackend",
    "QtNarratorAudioOutput",
    "QtPortalScreenCastBackend",
    "QtScreenCastPortal",
    "ScreenCaptureProvider",
    "SubtitleRegionStabilizer",
    "SubtitleSource",
    "TranslationCache",
    "TranslationProvider",
    "TtsProvider",
    "TESSERACT_COMPONENT_ID",
    "TESSERACT_MODEL_RELATIVE_PATH",
    "TesseractOcrProvider",
    "ARGOS_TRANSLATION_COMPONENT_ID",
    "ARGOS_TRANSLATION_MODEL_VERSION",
    "ARGOS_TRANSLATION_PROVIDER_ID",
    "ArgosCTranslate2TranslationProvider",
    "PIPER_COMPONENT_ID",
    "PIPER_CONFIG_RELATIVE_PATH",
    "PIPER_MODEL_RELATIVE_PATH",
    "PIPER_PROVIDER_ID",
    "PIPER_VOICE_ID",
    "PIPER_VOICE_VERSION",
    "POLISH_VOICES",
    "PiperPolishTtsProvider",
    "PolishVoice",
    "UnavailableAudioOutput",
    "UnavailableOcrProvider",
    "UnavailableTranslationProvider",
    "UnavailableTtsProvider",
    "crop_frame",
    "normalize_cache_phrase",
    "normalize_subtitle",
    "PnmStreamDecoder",
    "ANALYSIS_STATE_FILE_NAME",
    "ANALYSIS_STATE_SCHEMA_VERSION",
    "OptimizationAnalysisRepository",
    "AUTOMATIC_OPTIMIZATION_FILE_NAME",
    "AUTOMATIC_OPTIMIZATION_SCHEMA_VERSION",
    "AutomaticOptimizationEvaluator",
    "AutomaticOptimizationPlan",
    "AutomaticOptimizationRepository",
    "AutomaticOptimizationResult",
    "CandidateApplicability",
    "OptimizationProblem",
    "RuntimeCandidateRegistry",
    "RuntimeOptimizationCandidate",
    "diagnose_problem",
    "optimization_context_hash",
    "verify_runtime_activation",
    "GameRecommendationEngine",
    "OptimizationChangeService",
    "compare_measurements",
    "OPTIMIZATION_FILE_NAME",
    "GameRuntimeLaunchPlan",
    "OptimizationLaunchPlanner",
    "OPTISCALER_MANIFEST_FORMAT_VERSION",
    "OptiScalerCancelled",
    "OptiScalerConflict",
    "OptiScalerConflictError",
    "OptiScalerError",
    "OptiScalerFilePlan",
    "OptiScalerInstallPlan",
    "OptiScalerProfileRepository",
    "OptiScalerService",
    "CachedOptiScalerArchive",
    "OptiScalerCacheError",
    "OptiScalerDownloadError",
    "OptiScalerMetadataError",
    "OptiScalerNetworkError",
    "OptiScalerOnlineError",
    "OptiScalerRelease",
    "OptiScalerReleaseAsset",
    "OptiScalerReleaseClient",
    "parse_latest_stable_release",
    "PROTON_TWEAKS_FILE_NAME",
    "ProtonTweaksError",
    "ProtonTweaksRepository",
    "RuntimeToolAvailability",
    "RuntimeToolDetector",
    "DEFAULT_RUNNER_PATH",
    "RunnerIntegration",
    "RunnerStatus",
    "SevenZipArchiveReader",
    "InvalidTaskTransitionError",
    "InvalidAnalysisPath",
    "CACHE_FORMAT_VERSION",
    "LibraryCache",
    "LibraryCacheError",
    "MANGOHUD_CONFIG_FILE_NAME",
    "FLATPAK_MANGOHUD_PREFIX",
    "FLATPAK_STEAM_APP_ID",
    "KNOWN_CONFIG_KEYS",
    "METRIC_CONFIG_KEYS",
    "MangoHudAvailability",
    "MangoHudApplicationConfigStatus",
    "MangoHudConfigWriter",
    "MangoHudDetector",
    "MangoHudLaunchActivation",
    "MangoHudLaunchIntegration",
    "MangoHudProfileRepository",
    "ExecutableCandidate",
    "ExecutableResolution",
    "GameExecutableResolver",
    "MockBackupService",
    "MockTaskService",
    "PROFILE_LEVELS",
    "ProfileEstimate",
    "SettingsStore",
    "SettingsStoreError",
    "TaskNotFoundError",
    "TaskHistoryStore",
    "MAX_FINISHED_TASKS",
    "PrivilegedMeasurementClient",
    "PrivilegedMeasurementError",
    "measurement_delta",
    "current_compression_saving",
    "normalized_benchmark_projection",
    "merge_wine_dll_overrides",
    "aggregate_library_compression",
    "classify_compression_effect",
    "compression_effect",
    "has_high_shared_extent_risk",
    "reclaimed_by_last_operation",
    "TaskService",
    "TaskServiceError",
    "demo_backups",
    "FeatureUnavailableError",
    "GamepadInputMapper",
    "GamepadService",
    "FileFingerprint",
    "FingerprintLimits",
    "FingerprintSnapshot",
    "GameChangeSet",
    "GameFingerprintScanner",
    "GameUpdateRecord",
    "GameArtworkResolver",
    "HOST_SERVICE_VERSION",
    "OPTIONAL_MEASUREMENT_HELPER",
    "HostServiceClient",
    "HostServiceError",
    "HostBootstrapError",
    "HostBootstrapResult",
    "bootstrap_flatpak_host_components",
    "default_runner_path",
    "host_home_directory",
    "ResolvedGameArtwork",
    "GameUpdateStateStore",
    "GameUpdateStatus",
    "GameUpdateTracker",
    "ManifestObservation",
    "SteamLaunchError",
    "SteamLaunchPlan",
    "SteamLauncher",
    "UnavailableBackupService",
    "UnavailableTaskService",
    "UiSoundService",
    "UpdateDisplayStateStore",
    "UPDATE_STATE_FORMAT_VERSION",
    "UpdateScanCancelled",
    "UpdateStateDatabase",
    "UpdateStateStoreError",
    "build_steam_launch_command",
    "build_steam_launch_plan",
    "uses_flatpak_steam",
    "ZipArchiveReader",
    "diff_fingerprints",
    "open_archive",
]
